In [0]:
import numpy as np
import pandas as pd


In [0]:
df=pd.read_csv('/content/train.csv')

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3235 entries, 0 to 3234
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               3235 non-null   float64
 1   original_text    3235 non-null   object 
 2   lang             3231 non-null   object 
 3   retweet_count    3231 non-null   object 
 4   original_author  3235 non-null   object 
 5   sentiment_class  3235 non-null   int64  
dtypes: float64(1), int64(1), object(4)
memory usage: 151.8+ KB


In [243]:
df.head()

id  ... sentiment_class
0  1.245025e+18  ...               0
1  1.245759e+18  ...               0
2  1.246087e+18  ...              -1
3  1.244803e+18  ...               0
4  1.244876e+18  ...              -1

[5 rows x 6 columns]

In [244]:
df.describe()

id  sentiment_class
count  3.235000e+03      3235.000000
mean   1.245344e+18        -0.001236
std    8.014866e+14         0.688719
min    1.243909e+18        -1.000000
25%    1.244672e+18         0.000000
50%    1.245406e+18         0.000000
75%    1.246039e+18         0.000000
max    1.246734e+18         1.000000

In [245]:
#df['sentiment_class'].count()
print("1    ",df['sentiment_class'].value_counts())
print("------------------------------------------------------------")
print("2.    ",df['id'].value_counts())
print("------------------------------------------------------------")
print("3.   ",df['original_author'].value_counts() )
print("------------------------------------------------------------")
print("4.   ",df['retweet_count'].value_counts())
print("------------------------------------------------------------")
print("5.   ",df['original_text'].value_counts())
print("------------------------------------------------------------")
print("6.   ",df['lang'].value_counts())


1      0    1701
-1     769
 1     765
Name: sentiment_class, dtype: int64
------------------------------------------------------------
2.     1.246217e+18    1
1.246121e+18    1
1.246485e+18    1
1.246138e+18    1
1.246722e+18    1
               ..
1.245441e+18    1
1.244747e+18    1
1.245156e+18    1
1.246464e+18    1
1.245802e+18    1
Name: id, Length: 3235, dtype: int64
------------------------------------------------------------
3.    LToddWood          369
0                  146
MoM_Mastering       99
andreaanderegg      86
LiveGoodProduct     71
                  ... 
MandyMiracle1        1
ryanandamyshow       1
momtessorian1        1
lovemasamihair       1
cin_oh_cin           1
Name: original_author, Length: 1574, dtype: int64
------------------------------------------------------------
4.    0                2521
1                 291
en                142
2                  84
3                  45
                 ... 
25                  1
0.704111013         1
-0.539111

In [246]:
print("3.   ",df['original_author'].value_counts() )
df.head()

3.    LToddWood          369
0                  146
MoM_Mastering       99
andreaanderegg      86
LiveGoodProduct     71
                  ... 
MandyMiracle1        1
ryanandamyshow       1
momtessorian1        1
lovemasamihair       1
cin_oh_cin           1
Name: original_author, Length: 1574, dtype: int64


id  ... sentiment_class
0  1.245025e+18  ...               0
1  1.245759e+18  ...               0
2  1.246087e+18  ...              -1
3  1.244803e+18  ...               0
4  1.244876e+18  ...              -1

[5 rows x 6 columns]

In [0]:
# temp=df.loc[df['original_author']=='MoM_Mastering']
# print(temp['retweet_count'].value_counts())
# temp['sentiment_class'].value_counts()
# from sklearn.preprocessing import LabelEncoder
# converter=LabelEncoder()


In [0]:
temp=[]
row=0
for i in df['retweet_count']:
  try:
    temp.append(int(i))
    row+=1
  except:
    df.drop([row],inplace=True)
    row+=1



In [248]:
df.shape

(3053, 6)

In [0]:
df['retweet_count']=temp


In [0]:
# temp_original_author=converter.fit_transform(df.iloc[:,4])
# df['original_author']=temp_original_author

# df.head()




In [250]:
df.drop(['original_text', 'lang','original_author'], axis=1,inplace=True)  
df.corr()

id  retweet_count  sentiment_class
id               1.000000      -0.017429         0.012210
retweet_count   -0.017429       1.000000         0.020816
sentiment_class  0.012210       0.020816         1.000000

In [252]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(df.iloc[:,:2],df['sentiment_class'])


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [255]:
from sklearn.metrics import confusion_matrix
predicted_value=model.predict(df.iloc[:,:2])
con=confusion_matrix(df["sentiment_class"], predicted_value)
print(con)

[[ 684   63   22]
 [  35 1453   31]
 [  25   93  647]]


## Testing on Test dataset

In [256]:
test_df=pd.read_csv("/content/test.csv")
test_df.head()

id  ...  original_author
0  1.246628e+18  ...        LToddWood
1  1.245898e+18  ...        iiarushii
2  1.244717e+18  ...   andreaanderegg
3  1.245730e+18  ...  TheBookTweeters
4  1.244636e+18  ...   andreaanderegg

[5 rows x 5 columns]

In [257]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1387 entries, 0 to 1386
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   id               1387 non-null   float64
 1   original_text    1387 non-null   object 
 2   lang             1387 non-null   object 
 3   retweet_count    1386 non-null   object 
 4   original_author  1387 non-null   object 
dtypes: float64(1), object(4)
memory usage: 54.3+ KB


## Drop the unwanted columns 

In [0]:
test_df.drop(['original_text', 'lang','original_author'], axis=1,inplace=True)

In [259]:
test_df.head()

id retweet_count
0  1.246628e+18             0
1  1.245898e+18             0
2  1.244717e+18             0
3  1.245730e+18             1
4  1.244636e+18             0

In [0]:
temp=[]
row=0
for i in test_df['retweet_count']:
  try:
    temp.append(int(i))
    row+=1
  except:
    test_df.drop([row],inplace=True)
    row+=1

In [261]:
test_df.shape

(1324, 2)

In [0]:
predict_y=np.array(model.predict(test_df)).reshape(-1,1)
print(predict_y)

In [0]:
new_df=pd.DataFrame(test_df['id'],columns=['id'])
new_df['sentiment_class']=predict_y

In [0]:
new_df.to_csv('/content/drive/My Drive/Colab Notebooks/Hacker rank sentiment prediction/sentiment_class_prediction.csv', index=False)

In [289]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
